spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:43306/minisite
    driver-class-name: org.mariadb.jdbc.Driver
    username: minisite_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: sooin03@gmail.com
    password: qzxspyryhttpppay
    properties:
      mail:
        smtp:
          starttls:
            enable: true

logging:
   level:
     root: info